import streamlit as st
from dotenv import load_dotenv

from langchain_ollama import ChatOllama
from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_core.prompts import (
    ChatPromptTemplate,
    MessagesPlaceholder
)

from langchain_core.messages import (
    HumanMessage,
    AIMessage
)

from langchain_core.output_parsers import (
    StrOutputParser
)


load_dotenv()


st.set_page_config(
    page_title="Hybrid LLM Research Assistant",
    page_icon="🧠",
    layout="wide"
)

st.markdown("""
<style>

.main {
    background-color: #0E1117;
    color: white;
}

.stChatMessage {
    border-radius: 12px;
    padding: 10px;
    margin-bottom: 10px;
}

h1 {
    text-align: center;
    color: #8B5CF6;
}

.block-container {
    padding-top: 2rem;
}

</style>
""", unsafe_allow_html=True)


st.title(" Hybrid LLM Research Assistant")

st.markdown(
        """
    <p style="text-align:center; color:gray; font-size:14px;">
        <strong>Primary:</strong> Gemini 2.5 Flash &nbsp;|&nbsp;
        <strong>Fallback:</strong> Llama3:8B (Ollama) &nbsp;|&nbsp;
        <strong>Powered by:</strong> LangChain + Streamlit
    </p>
    """,
    
    unsafe_allow_html=True
)


with st.sidebar:

    st.header("⚙️ Controls")

    if st.button("🗑️ Clear Chat"):
        st.session_state.chat_history = []
        st.rerun()

    st.divider()

    st.markdown("### 🤖 Models")

    st.info("""
Primary Model:
Gemini 2.5 Flash

Fallback Model:
Llama3:8B (Ollama)
""")

    st.divider()

    st.markdown("""
### 📌 Features

✅ Cloud LLM

✅ Local LLM Fallback

✅ Chat Memory

✅ Local Execution

✅ Research Assistant

✅ Production Ready
""")


parser = StrOutputParser()


cloud_llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.7
)


local_llm = ChatOllama(
    model="llama3:8b",
    temperature=0.7
)


prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """
You are an expert AI Research Assistant.

When user gives a topic:

1. Give a clear 3-line summary

2. List 3 key points

3. Give 1 real world application

4. Ask if user wants to explore any specific area

Keep responses structured and concise.
"""
    ),

    MessagesPlaceholder(variable_name="history"),

    ("human", "{input}")
])


cloud_chain = prompt | cloud_llm | parser

local_chain = prompt | local_llm | parser


if "chat_history" not in st.session_state:
    st.session_state.chat_history = []


for message in st.session_state.chat_history:

    if isinstance(message, HumanMessage):
        with st.chat_message("user"):
            st.markdown(message.content)

    elif isinstance(message, AIMessage):
        with st.chat_message("assistant"):
            st.markdown(message.content)

user_input = st.chat_input(
    "Ask any research topic..."
)

if user_input:

    with st.chat_message("user"):
        st.markdown(user_input)


    st.session_state.chat_history.append(
        HumanMessage(content=user_input)
    )

    with st.chat_message("assistant"):

        with st.spinner("🔍 Researching..."):

            try:


                response = cloud_chain.invoke({
                    "history": st.session_state.chat_history,
                    "input": user_input
                })

                st.caption(
                    "☁️ Response generated by Gemini"
                )

            except Exception as e:

                st.warning(
                    "⚠️ Cloud model unavailable. Switching to local model..."
                )


                response = local_chain.invoke({
                    "history": st.session_state.chat_history,
                    "input": user_input
                })

                st.caption(
                    "💻 Response generated by Ollama(llama3:8b)"
                )

            st.markdown(response)

   
    st.session_state.chat_history.append(
        AIMessage(content=response)
    )